dist: jammy
language: node_js
node_js:
  - "node"
branches:
  except:
  - gh-pages
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - nyc --reporter=lcov mocha --require babel-core/register
after_success:
  - nyc report --reporter=text-lcov | coveralls                     # report to Coveralls
  - nyc report --reporter=text-lcov > coverage.lcov && codecov      # report to Codecov
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT  # report to Code Climate
  - webpack   # prepare for deployment
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local-dir: dist
  on:
    branch: master
after_script:
  - echo 'done!'
